/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bookings.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the City service. Represents a row in the &quot;City&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.bookings.model.impl.CityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.bookings.model.impl.CityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see City
 * @generated
 */
@ProviderType
public interface CityModel extends BaseModel<City> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a city model instance should use the {@link City} interface instead.
	 */

	/**
	 * Returns the primary key of this city.
	 *
	 * @return the primary key of this city
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this city.
	 *
	 * @param primaryKey the primary key of this city
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this city.
	 *
	 * @return the uuid of this city
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this city.
	 *
	 * @param uuid the uuid of this city
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the city_id of this city.
	 *
	 * @return the city_id of this city
	 */
	public long getCity_id();

	/**
	 * Sets the city_id of this city.
	 *
	 * @param city_id the city_id of this city
	 */
	public void setCity_id(long city_id);

	/**
	 * Returns the city_ name of this city.
	 *
	 * @return the city_ name of this city
	 */
	@AutoEscape
	public String getCity_Name();

	/**
	 * Sets the city_ name of this city.
	 *
	 * @param city_Name the city_ name of this city
	 */
	public void setCity_Name(String city_Name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(City city);

	@Override
	public int hashCode();

	@Override
	public CacheModel<City> toCacheModel();

	@Override
	public City toEscapedModel();

	@Override
	public City toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}