/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bookings.model;

import aQute.bnd.annotation.ProviderType;

import com.bookings.service.persistence.Movies_CityPK;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Movies_City service. Represents a row in the &quot;Movies_City&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.bookings.model.impl.Movies_CityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.bookings.model.impl.Movies_CityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Movies_City
 * @generated
 */
@ProviderType
public interface Movies_CityModel extends BaseModel<Movies_City> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a movies_ city model instance should use the {@link Movies_City} interface instead.
	 */

	/**
	 * Returns the primary key of this movies_ city.
	 *
	 * @return the primary key of this movies_ city
	 */
	public Movies_CityPK getPrimaryKey();

	/**
	 * Sets the primary key of this movies_ city.
	 *
	 * @param primaryKey the primary key of this movies_ city
	 */
	public void setPrimaryKey(Movies_CityPK primaryKey);

	/**
	 * Returns the movie_id of this movies_ city.
	 *
	 * @return the movie_id of this movies_ city
	 */
	public long getMovie_id();

	/**
	 * Sets the movie_id of this movies_ city.
	 *
	 * @param movie_id the movie_id of this movies_ city
	 */
	public void setMovie_id(long movie_id);

	/**
	 * Returns the city_id of this movies_ city.
	 *
	 * @return the city_id of this movies_ city
	 */
	public long getCity_id();

	/**
	 * Sets the city_id of this movies_ city.
	 *
	 * @param city_id the city_id of this movies_ city
	 */
	public void setCity_id(long city_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Movies_City movies_City);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Movies_City> toCacheModel();

	@Override
	public Movies_City toEscapedModel();

	@Override
	public Movies_City toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}