/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bookings.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Movies service. Represents a row in the &quot;Movies&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.bookings.model.impl.MoviesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.bookings.model.impl.MoviesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Movies
 * @generated
 */
@ProviderType
public interface MoviesModel extends BaseModel<Movies> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a movies model instance should use the {@link Movies} interface instead.
	 */

	/**
	 * Returns the primary key of this movies.
	 *
	 * @return the primary key of this movies
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this movies.
	 *
	 * @param primaryKey the primary key of this movies
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this movies.
	 *
	 * @return the uuid of this movies
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this movies.
	 *
	 * @param uuid the uuid of this movies
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this movies.
	 *
	 * @return the ID of this movies
	 */
	public long getId();

	/**
	 * Sets the ID of this movies.
	 *
	 * @param id the ID of this movies
	 */
	public void setId(long id);

	/**
	 * Returns the name of this movies.
	 *
	 * @return the name of this movies
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this movies.
	 *
	 * @param name the name of this movies
	 */
	public void setName(String name);

	/**
	 * Returns the rating of this movies.
	 *
	 * @return the rating of this movies
	 */
	public Double getRating();

	/**
	 * Sets the rating of this movies.
	 *
	 * @param rating the rating of this movies
	 */
	public void setRating(Double rating);

	/**
	 * Returns the release_date of this movies.
	 *
	 * @return the release_date of this movies
	 */
	public Date getRelease_date();

	/**
	 * Sets the release_date of this movies.
	 *
	 * @param release_date the release_date of this movies
	 */
	public void setRelease_date(Date release_date);

	/**
	 * Returns the length_min of this movies.
	 *
	 * @return the length_min of this movies
	 */
	public int getLength_min();

	/**
	 * Sets the length_min of this movies.
	 *
	 * @param length_min the length_min of this movies
	 */
	public void setLength_min(int length_min);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Movies movies);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Movies> toCacheModel();

	@Override
	public Movies toEscapedModel();

	@Override
	public Movies toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}